default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cookit_rails_development

test:
  <<: *default
  database: cookit_rails_test

production:
  <<: *default
  database: cookit_rails_production
  username: cookit_rails
  password: <%= ENV['COOKIT_RAILS_DATABASE_PASSWORD'] %>
